CALL newgame('Animal Crossing: New Leaf','Simulation','Nintendo EAD',38.41,'https://www.vgchartz.com/games/boxart/full_7774244AmericaFrontccc.jpg');
CALL newgame('Animal Crossing: Wild World','Simulation','Nintendo EAD',22.47,'https://www.vgchartz.com/games/boxart/full_8328377AmericaFrontccc.jpg');
CALL newgame('Brain Age 2: More Training in Minutes a Day','Misc','Nintendo SDD',17.75,'https://www.vgchartz.com/games/boxart/full_1039696AmericaFrontccc.jpg');
CALL newgame('Brain Age: Train Your Brain in Minutes a Day','Misc','Nintendo SDD',34.08,'https://www.vgchartz.com/games/boxart/full_7749365AmericaFrontccc.jpg');
CALL newgame('Call of Duty 4: Modern Warfare','Shooter','Infinity Ward',39.96,'https://www.vgchartz.com/games/boxart/full_4481633AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Black Ops 3','Shooter','Treyarch',42.5,'https://www.vgchartz.com/games/boxart/full_4990510AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Black Ops II','Shooter','Treyarch',10.31,'https://www.vgchartz.com/games/boxart/full_1977964AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Black Ops IIII','Shooter','Treyarch',43.37,'https://www.vgchartz.com/games/boxart/full_6532460AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Black Ops','Shooter','Treyarch',26.06,'https://www.vgchartz.com/games/boxart/full_call-of-duty-black-ops_5AmericaFront.jpg');
CALL newgame('Call of Duty: Ghosts','Shooter','Infinity Ward',11.65,'https://www.vgchartz.com/games/boxart/full_8522439AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Infinite Warfare','Shooter','Infinity Ward',30.76,'https://www.vgchartz.com/games/boxart/full_5706058AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Modern Warfare 2','Shooter','Infinity Ward',48.47,'https://www.vgchartz.com/games/boxart/full_809251AmericaFrontccc.jpg');
CALL newgame('Call of Duty: Modern Warfare 3','Shooter','Infinity Ward',42.51,'https://www.vgchartz.com/games/boxart/full_call-of-duty-modern-warfare-3_517AmericaFront.jpg');
CALL newgame('Call of Duty: WWII','Shooter','Sledgehammer Games',42.18,'https://www.vgchartz.com/games/boxart/full_4380292AmericaFrontccc.jpg');
CALL newgame('Counter-Strike: Source','Shooter','Valve Software',45.87,'https://www.vgchartz.com/games/boxart/full_9030886AmericaFrontccc.jpg');
CALL newgame('Diablo III','Role-Playing','Blizzard Entertainment',18.41,'https://www.vgchartz.com/games/boxart/full_diablo-iii_550AmericaFront.jpg');
CALL newgame('Donkey Kong Country','Platform','Rare Ltd.',22.94,'https://www.vgchartz.com/games/boxart/6431319ccc.jpg');
CALL newgame('Duck Hunt','Shooter','Nintendo R&D1',23.62,'https://www.vgchartz.com/games/boxart/full_6570468AmericaFrontccc.jpg');
CALL newgame('Fallout 4','Role-Playing','Bethesda Game Studios',39.98,'https://www.vgchartz.com/games/boxart/full_2507140AmericaFrontccc.jpg');
CALL newgame('FIFA 16','Sports','EA Canada',32.18,'https://www.vgchartz.com/games/boxart/full_862315AmericaFrontccc.jpg');
CALL newgame('FIFA 17','Sports','EA Canada',46.62,'https://www.vgchartz.com/games/boxart/full_7661370AmericaFrontccc.jpg');
CALL newgame('FIFA 18','Sports','EA Vancouver',27.04,'https://www.vgchartz.com/games/boxart/full_5257064AmericaFrontccc.jpg');
CALL newgame('FIFA 19','Sports','EA Sports',47.25,'https://www.vgchartz.com/games/boxart/full_5970958AmericaFrontccc.jpg');
CALL newgame('Final Fantasy VII','Role-Playing','SquareSoft',15.28,'https://www.vgchartz.com/games/boxart/1190945ccc.jpg');
CALL newgame('Final Fantasy VIII','Role-Playing','SquareSoft',11.15,'https://www.vgchartz.com/games/boxart/1184295ccc.jpg');
CALL newgame('Final Fantasy X','Role-Playing','SquareSoft',46.07,'https://www.vgchartz.com/games/boxart/4912276ccc.jpg');
CALL newgame('Garry''s Mod','Misc','Team Garry',16.04,'https://www.vgchartz.com/games/boxart/full_6480469AmericaFrontccc.jpg');
CALL newgame('GoldenEye 007','Shooter','Rare Ltd.',37.52,'https://www.vgchartz.com/games/boxart/2952086ccc.jpg');
CALL newgame('Gran Turismo 2','Racing','Polyphony Digital',49.13,'https://www.vgchartz.com/games/boxart/45196ccc.jpg');
CALL newgame('Gran Turismo 3: A-Spec','Racing','Polyphony Digital',9.66,'https://www.vgchartz.com/games/boxart/full_5113832AmericaFrontccc.jpg');
CALL newgame('Gran Turismo 4','Racing','Polyphony Digital',10.63,'https://www.vgchartz.com/games/boxart/full_8555381AmericaFrontccc.jpg');
CALL newgame('Gran Turismo 5','Racing','Polyphony Digital',30.59,'https://www.vgchartz.com/games/boxart/full_gran-turismo-5_118AmericaFront.png');
CALL newgame('Gran Turismo','Racing','Polyphony Digital',25.93,'https://www.vgchartz.com/games/boxart/6215143ccc.jpg');
CALL newgame('Grand Theft Auto III','Action','DMA Design',32.57,'https://www.vgchartz.com/games/boxart/3570928ccc.jpg');
CALL newgame('Grand Theft Auto IV','Action','Rockstar North',37.86,'https://www.vgchartz.com/games/boxart/full_1182151AmericaFrontccc.jpg');
CALL newgame('Grand Theft Auto V','Action','Rockstar North',37.95,'https://www.vgchartz.com/games/boxart/full_6510540AmericaFrontccc.jpg');
CALL newgame('Grand Theft Auto: San Andreas','Action','Rockstar North',20.29,'https://www.vgchartz.com/games/boxart/3887656ccc.jpg');
CALL newgame('Grand Theft Auto: Vice City','Action','Rockstar North',38.51,'https://www.vgchartz.com/games/boxart/827563ccc.jpg');
CALL newgame('Half-Life 2','Shooter','Valve Software',22.07,'https://www.vgchartz.com/games/boxart/6354662ccc.jpg');
CALL newgame('Halo 3','Shooter','Bungie Studios',39.49,'https://www.vgchartz.com/games/boxart/full_8373567AmericaFrontccc.jpg');
CALL newgame('Halo 4','Shooter','343 Industries',29.91,'https://www.vgchartz.com/games/boxart/full_2236292AmericaFrontccc.png');
CALL newgame('Halo: Reach','Shooter','Bungie',32.08,'https://www.vgchartz.com/games/boxart/full_halo-reach_6AmericaFront.jpg');
CALL newgame('Horizon: Zero Dawn','Action','Guerrilla Games',47.88,'https://www.vgchartz.com/games/boxart/full_719511AmericaFrontccc.jpg');
CALL newgame('Just Dance 3','Misc','Ubisoft Paris',20.95,'https://www.vgchartz.com/games/boxart/full_just-dance-3_883AmericaFront.jpg');
CALL newgame('Kinect Adventures!','Party','Good Science Studio',32.08,'https://www.vgchartz.com/games/boxart/full_kinect-adventures_386AmericaFront.jpg');
CALL newgame('Mario Kart 64','Racing','Nintendo EAD',11.58,'https://www.vgchartz.com/games/boxart/full_8835641AmericaFrontccc.jpg');
CALL newgame('Mario Kart 8 Deluxe','Racing','Nintendo EPD',21.7,'https://www.vgchartz.com/games/boxart/full_895207AmericaFrontccc.png');
CALL newgame('Mario Kart 8','Racing','Nintendo',27.64,'https://www.vgchartz.com/games/boxart/full_638065AmericaFrontccc.jpg');
CALL newgame('Mario Kart DS','Racing','Nintendo EAD',45.49,'https://www.vgchartz.com/games/boxart/full_9551652AmericaFrontccc.jpg');
CALL newgame('Mario Kart Wii','Racing','Nintendo EAD',46.61,'https://www.vgchartz.com/games/boxart/full_8932480AmericaFrontccc.jpg');
CALL newgame('Mario Party 8','Misc','Hudson Soft',32.65,'https://www.vgchartz.com/games/boxart/full_7451822AmericaFrontccc.jpg');
CALL newgame('Mario Party DS','Misc','Hudson Soft',21.45,'https://www.vgchartz.com/games/boxart/full_7340729AmericaFrontccc.jpg');
CALL newgame('Marvel''s Spider-Man','Action-Adventure','Insomniac Games',22.32,'https://www.vgchartz.com/games/boxart/full_7960565AmericaFrontccc.jpg');
CALL newgame('Minecraft','Misc','Mojang AB',11.72,'https://www.vgchartz.com/games/boxart/full_minecraft_1AmericaFront.png');
CALL newgame('New Super Mario Bros. 2','Platform','Nintendo',34.49,'https://www.vgchartz.com/games/boxart/full_9872028AmericaFrontccc.jpg');
CALL newgame('New Super Mario Bros. Wii','Platform','Nintendo EAD',27.43,'https://www.vgchartz.com/games/boxart/full_1410872AmericaFrontccc.jpg');
CALL newgame('New Super Mario Bros.','Platform','Nintendo EAD',21.71,'https://www.vgchartz.com/games/boxart/full_2916260AmericaFrontccc.jpg');
CALL newgame('Nintendogs','Simulation','Nintendo EAD',34.63,'https://www.vgchartz.com/games/boxart/full_4870931AmericaFrontccc.jpg');
CALL newgame('PlayerUnknown''s Battlegrounds','Shooter','PUBG Corporation',32,'https://www.vgchartz.com/games/boxart/full_8052843AmericaFrontccc.jpg');
CALL newgame('Pokemon Black / White Version','Role-Playing','Game Freak',36,'https://www.vgchartz.com/games/boxart/full_2983232AmericaFrontccc.jpg');
CALL newgame('Pokemon Black 2 and White 2','Role-Playing','Game Freak',23.89,'https://www.vgchartz.com/games/boxart/full_3674437AmericaFrontccc.png');
CALL newgame('Pokemon Diamond / Pearl Version','Role-Playing','Game Freak',28.99,'https://www.vgchartz.com/games/boxart/full_2730687AmericaFrontccc.jpg');
CALL newgame('Pokemon FireRed / LeafGreen Version','Role-Playing','Game Freak',43.75,'https://www.vgchartz.com/games/boxart/full_5668335AmericaFrontccc.jpg');
CALL newgame('Pokemon Gold / Silver Version','Role-Playing','Game Freak',37.95,'https://www.vgchartz.com/games/boxart/full_1344180AmericaFrontccc.png');
CALL newgame('Pokemon Heart Gold / Soul Silver Version','Role-Playing','Game Freak',38.1,'https://www.vgchartz.com/games/boxart/full_2733841AmericaFrontccc.jpg');
CALL newgame('Pokemon Omega Ruby/Pokemon Alpha Sapphire','Role-Playing','Game Freak',49.82,'https://www.vgchartz.com/games/boxart/full_5184866AmericaFrontccc.png');
CALL newgame('Pokemon Red / Green / Blue Version','Role-Playing','Game Freak',34.51,'https://www.vgchartz.com/games/boxart/full_6442337AmericaFrontccc.png');
CALL newgame('Pokemon Ruby / Sapphire Version','Role-Playing','Game Freak',26.83,'https://www.vgchartz.com/games/boxart/full_4771333AmericaFrontccc.png');
CALL newgame('Pokemon Sun/Moon','Role-Playing','Game Freak',11.84,'https://www.vgchartz.com/games/boxart/full_6532288JapanFrontccc.png');
CALL newgame('Pokemon X/Y','Role-Playing','Game Freak',48.22,'https://www.vgchartz.com/games/boxart/full_9470074AmericaFrontccc.png');
CALL newgame('Pokemon Yellow: Special Pikachu Edition','Role-Playing','Game Freak',31.73,'https://www.vgchartz.com/games/boxart/4260472ccc.jpg');
CALL newgame('Pokemon: Let''s Go, Pikachu/Eevee','Role-Playing','Game Freak',20.18,'https://www.vgchartz.com/games/boxart/full_2669309AmericaFrontccc.jpg');
CALL newgame('Pokemon: Ultra Sun and Ultra Moon','Role-Playing','Game Freak',44.4,'https://www.vgchartz.com/games/boxart/full_9155401AmericaFrontccc.png');
CALL newgame('Portal 2','Shooter','Valve Software',27.7,'https://www.vgchartz.com/games/boxart/full_portal-2_617AmericaFront.jpg');
CALL newgame('Portal','Shooter','Valve Software',17.1,'https://www.vgchartz.com/games/boxart/5574270ccc.jpg');
CALL newgame('Red Dead Redemption 2','Action-Adventure','Rockstar Games',23.52,'https://www.vgchartz.com/games/boxart/full_4653215AmericaFrontccc.jpg');
CALL newgame('RollerCoaster Tycoon 3','Strategy','Frontier Developments',38.01,'https://www.vgchartz.com/games/boxart/full_6560922AmericaFrontccc.jpg');
CALL newgame('Rust','Action-Adventure','Facepunch Studios',42.01,'https://www.vgchartz.com/games/boxart/full_9200722AmericaFrontccc.jpg');
CALL newgame('Sonic the Hedgehog','Platform','Sonic Team',46.85,'https://www.vgchartz.com/games/boxart/4697634ccc.jpg');
CALL newgame('Splatoon 2','Shooter','Nintendo EPD',15.07,'https://www.vgchartz.com/games/boxart/full_7536933AmericaFrontccc.png');
CALL newgame('StarCraft','Strategy','Blizzard Entertainment',28.11,'https://www.vgchartz.com/games/boxart/3959329ccc.jpg');
CALL newgame('Super Mario 3D Land','Platform','Nintendo EAD Tokyo',44.39,'https://www.vgchartz.com/games/boxart/full_super-mario-3dland_167AmericaFront.jpg');
CALL newgame('Super Mario 64 DS','Platform','Nintendo EAD',38.08,'https://www.vgchartz.com/games/boxart/full_1719347AmericaFrontccc.jpg');
CALL newgame('Super Mario 64','Platform','Nintendo EAD',22.92,'https://www.vgchartz.com/games/boxart/full_9007863AmericaFrontccc.jpg');
CALL newgame('Super Mario All-Stars','Platform','Nintendo EAD',25.19,'https://www.vgchartz.com/games/boxart/8836826ccc.jpg');
CALL newgame('Super Mario Bros. 3','Platform','Nintendo R&D2',44.06,'https://www.vgchartz.com/games/boxart/4113056ccc.jpg');
CALL newgame('Super Mario Bros.','Platform','Nintendo EAD',28.67,'https://www.vgchartz.com/games/boxart/8972270ccc.jpg');
CALL newgame('Super Mario Galaxy','Platform','Nintendo EAD Tokyo',27.67,'https://www.vgchartz.com/games/boxart/full_5542974AmericaFrontccc.jpg');
CALL newgame('Super Mario Kart','Racing','Nintendo EAD',31.85,'https://www.vgchartz.com/games/boxart/full_3980311AmericaFrontccc.jpg');
CALL newgame('Super Mario Land 2: 6 Golden Coins','Platform','Nintendo R&D1',11.45,'https://www.vgchartz.com/games/boxart/full_5947486AmericaFrontccc.jpg');
CALL newgame('Super Mario Land','Platform','Nintendo R&D1',24.85,'https://www.vgchartz.com/games/boxart/3345559ccc.jpg');
CALL newgame('Super Mario Odyssey','Platform','Nintendo EPD',16.5,'https://www.vgchartz.com/games/boxart/full_1659701AmericaFrontccc.jpg');
CALL newgame('Super Mario World','Platform','Nintendo EAD',45.7,'https://www.vgchartz.com/games/boxart/full_1091265AmericaFrontccc.jpg');
CALL newgame('Super Smash Bros. Brawl','Fighting','Project Sora',35.01,'https://www.vgchartz.com/games/boxart/full_4169332AmericaFrontccc.jpg');
CALL newgame('Super Smash Bros. for 3DS','Fighting','Bandai Namco Games',25.77,'https://www.vgchartz.com/games/boxart/full_4463374AmericaFrontccc.jpg');
CALL newgame('Super Smash Bros. Ultimate','Fighting','Bandai Namco Games',50.01,'https://www.vgchartz.com/games/boxart/full_8423750AmericaFrontccc.jpg');
CALL newgame('Tekken 3','Fighting','Namco',10.92,'https://www.vgchartz.com/games/boxart/full_tekken-3_687AmericaFront.jpg');
CALL newgame('Terraria','Platform','Re-Logic',32.03,'https://www.vgchartz.com/games/boxart/full_terraria_497AmericaFront.jpg');
CALL newgame('Tetris','Puzzle','Bullet Proof Software',37.71,'https://www.vgchartz.com/games/boxart/3740960ccc.jpg');
CALL newgame('The Elder Scrolls V: Skyrim','Role-Playing','Bethesda Game Studios',12.89,'https://www.vgchartz.com/games/boxart/full_the-elder-scrolls-v-skyrim_554AmericaFront.jpg');
CALL newgame('The Legend of Zelda: Breath of the Wild','Action-Adventure','Nintendo EPD',27.5,'https://www.vgchartz.com/games/boxart/full_4436858AmericaFrontccc.png');
CALL newgame('Uncharted 4: A Thief''s End','Action','Naughty Dog',42.32,'https://www.vgchartz.com/games/boxart/full_2804791AmericaFrontccc.jpg');
CALL newgame('Wii Fit Plus','Sports','Nintendo EAD',47.03,'https://www.vgchartz.com/games/boxart/full_2716475AmericaFrontccc.jpg');
CALL newgame('Wii Fit','Sports','Nintendo EAD',18.68,'https://www.vgchartz.com/games/boxart/full_3619557AmericaFrontccc.jpg');
CALL newgame('Wii Party','Misc','Nd Cube Co., Ltd.',22.42,'https://www.vgchartz.com/games/boxart/full_wii-party_1AmericaFront.jpg');
CALL newgame('Wii Play','Misc','Nintendo EAD',11.22,'https://www.vgchartz.com/games/boxart/full_6165969AmericaFrontccc.jpg');
CALL newgame('Wii Sports Resort','Sports','Nintendo EAD',15.72,'https://www.vgchartz.com/games/boxart/full_7295041AmericaFrontccc.jpg');
CALL newgame('Wii Sports','Sports','Nintendo EAD',25.49,'https://www.vgchartz.com/games/boxart/full_2258645AmericaFrontccc.jpg');
